### ISSUE TITLE
`Strings.truncate` returns string with length 1 less than it should

### ISSUE THREAD

**Issue by justingaylor** [piotrmurach/strings#17]
Thank you for making this gem and your other terminal-friendly gems (tty, pastel, etc). I'm a fan of your work! 😃 

### Describe the problem

When truncating a string containing only single-width characters and no ansi codes, I noticed that it returns one less character than it should (even including the trailing character). For example, when I specify to truncate to 6 characters and add empty trailing, I receive back only 5 characters, not 6.

### Steps to reproduce the problem

Version 0.2.1
```
irb(main):008:0> require 'strings'
=> true
irb(main):009:0> Strings::VERSION
=> "0.2.1"
irb(main):010:0> Strings.truncate("+-----+", 7, trailing: '')
=> "+-----+"
irb(main):011:0> Strings.truncate("+-----+", 6, trailing: '')
=> "+----"
``` 

### Actual behaviour

When `truncate_at` is set to 7 above, it returns 7 characters. However, when I set it to 6, I actually only get back 5 characters.

### Expected behaviour

I expect when `truncate_at` is 6, it should cut the string off after 6 non-ansi characters (when empty `trailing` character specified). This appears to be what the examples in the README [here](https://github.com/piotrmurach/strings#26-truncate) show? Is this a bug or is the documentation correct? I see the specs test in some places check for one less character than `truncate_at` implying it might not be inclusive, but the docs (and behavior when specifying 7 above) seem to disagree. 

I will make a branch that adds some tests for this case (and updates a few others) to fix the perceived issue. Let me know if my understanding is correct and I can issue a PR. Thank you!

### Describe your environment

* OS version: macOS Big Sur (11.6)
* Ruby version: 2.6.3
* Strings version: 0.2.1

**Comment by piotrmurach** [comment]
Hi Justin 👋 

Thanks for your kind words and trying `strings` out!

The goal for `strings` gem is to tease out all the bits into separate [components](https://github.com/piotrmurach/strings#4-components). I've managed to extract the truncation component out to [strings-truncation](https://github.com/piotrmurach/strings-truncation). It's more powerful now in terms of features and compatibility with other components. 

Running your example, the result is correct:

```ruby
require "strings-truncation"

strings = Strings::Truncation.new
text = "I try all things, I achieve what I can"
trunc_at = 14
truncated_text = strings.truncate(text, trunc_at)
puts truncated_text.length == trunc_at # => true
```

And as I was writing this response, the steps have changed. So here are the results for the new example:

```ruby
>> strings.truncate("+-----+", 7, omission: "")
=> "+-----+"
>> strings.truncate("+-----+", 6, omission: "")
=> "+-----"
```

I must apologise to you for not making this clearer in the readme! I do hope to find more time to move with the extraction of the other bits so that `strings` itself becomes a meta gem for pulling in other components. If you find any issues with truncation please report them in the new component repo.
